name: ci

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - run: pnpm install
      - run: pnpm test
      - uses: davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all

  test-example-books-cli:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - run: pnpm install
      - run: pnpm build
      - working-directory: examples/books-cli
        run: pnpm install
      - working-directory: examples/books-cli
        run: pnpm build
      - working-directory: examples/books-cli
        run: pnpm test

  test-example-deno-simple:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41
      - working-directory: examples/deno-simple
        run: deno test

  test-example-jsonesit:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - run: pnpm install
      - run: pnpm build
      - working-directory: examples/jsonedit
        run: pnpm install
      - working-directory: examples/jsonedit
        run: pnpm build
      - working-directory: examples/jsonedit
        run: pnpm test
