type Book = {
  name: string;
  summary: string;
  pageCount: number;
  published: string;
}

/**
 * Note: These sentences are generated by chatgpt
 */
export const books: Book[] = [
  {
    name: 'Explore Paris',
    summary: 'Discover the beauty and culture of the City of Love.',
    pageCount: 200,
    published: '2022-03-15'
  },
  {
    name: 'Journey to the Grand Canyon',
    summary: 'Experience the breathtaking vistas of the Grand Canyon.',
    pageCount: 150,
    published: '2021-07-20'
  },
  {
    name: 'Adventures in Rome',
    summary: 'Immerse yourself in the history and cuisine of Rome.',
    pageCount: 180,
    published: '2022-01-10'
  },
  {
    name: 'Beaches of Bali',
    summary: 'Relax on the stunning beaches of Bali and explore its culture.',
    pageCount: 160,
    published: '2021-11-05'
  },
  {
    name: 'African Safari Tales',
    summary: 'Embark on a thrilling safari adventure in Africa.',
    pageCount: 220,
    published: '2022-06-30'
  },
  {
    name: 'Hiking the Swiss Alps',
    summary: 'Hike through the picturesque landscapes of the Swiss Alps.',
    pageCount: 170,
    published: '2021-09-18'
  },
  {
    name: 'Mysteries of Machu Picchu',
    summary: 'Uncover the secrets of the ancient Inca city in Peru.',
    pageCount: 190,
    published: '2022-04-25'
  },
  {
    name: 'Cruising the Caribbean',
    summary: 'Set sail on a Caribbean cruise and explore its islands.',
    pageCount: 140,
    published: '2021-12-12'
  },
  {
    name: 'A Taste of Thailand',
    summary: 'Experience the flavors and culture of Thailand.',
    pageCount: 175,
    published: '2022-02-28'
  },
  {
    name: 'Hiking the Rockies',
    summary: 'Discover the beauty of the Rocky Mountains through hiking.',
    pageCount: 155,
    published: '2021-10-09'
  }
]
